export * from './Skeleton';
export * from './SkeletonText';
export * from './SkeletonCard';
export * from './SkeletonMetric';
export * from './SkeletonTable';
export * from './SkeletonBulletins';
export * from './dashboards/StudentDashboardSkeleton';
export * from './dashboards/TeacherDashboardSkeleton';
export * from './dashboards/AdminDashboardSkeleton';
